### ISSUE TITLE
Backend has no IP protection

### ISSUE THREAD

**Issue by felix920506** [miyago9267/mygoapi#2]
domain "drive.miyago9267.com" is pointing directly at non protected IP leaving it vulnerable to attacks such as ddos

**Comment by miyago9267** [comment]
i know, it just a temporary method to storage static pictures.
we'll using some data mapping to rebuild out database soon.

**Comment by miyago9267** [comment]
The domain `drive.miyago9267.com` is already under cloudflare proxy.
