### ISSUE TITLE
File names with spaces (or other special characters) can cause issues

### ISSUE THREAD

**Issue by felix920506** [miyago9267/mygoapi#4]
As shown in the picture below, file names with spaces cause problems in some scenarios. They should be replaced with other characters such as "-" or "_" to improve compatibility. 
![image](https://github.com/user-attachments/assets/a05cbdc4-06e6-43ca-be02-4384796ec652)

**Comment by miyago9267** [comment]
got it. i would like to convert the link with url encode

**Comment by miyago9267** [comment]
Thx for opening issue, this issue has fixed in [#1c4a9d6](https://github.com/miyago9267/mygoapi/commit/1c4a9d6c87e23ce79356ac56f5f8d58bd5af0b2e)
