### ISSUE TITLE
Swagger docs link is empty

### ISSUE THREAD

**Issue by felix920506** [miyago9267/mygoapi#5]
as shown in picture
<img width="1512" alt="截圖 2024-08-30 晚上11 54 53" src="https://github.com/user-attachments/assets/c02f745b-e32c-40b6-90f4-e7e0ac514155">

**Comment by miyago9267** [comment]
Dude, it's in `https://mygoapi.miyago9267.com/docs`

**Comment by felix920506** [comment]
The link provided in the readme file is the link I opened in the screenshot
